version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./dataset:/code/dataset
      - ./ml_models:/code/ml_models
    environment:
      # host.docker.internal connects to your local PostgreSQL 18!
      # Assuming your password is 'postgresql' based on your .env file
      - POSTGRES_URL=postgresql://postgres:postgresql@host.docker.internal:5432/agrosync_db
      - REDIS_URL=redis://redis:6379/0
      - INFLUX_URL=http://influxdb:8086
    depends_on:
      # Removed 'db' from here
      - redis
      - influxdb

  # The "db" block is completely removed

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    env_file:
      - .env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin0611 
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
      
volumes:
  # Removed postgres_data volume
  redis_data:
  influxdb_data: